Repository piscibus/siklid-api, pull requests merged in 2023-04, with the labels that each got.

#227 [Flashcard] Delete flashcard
  src/Controller/FlashcardController.php
  src/Foundation/Http/Request.php
  src/Siklid/Application/Flashcard/DeleteFlashcard.php
  src/Siklid/Document/Flashcard.php
  tests/Concern/Assertion/AssertODMTrait.php
  tests/Concern/Factory/FlashcardFactoryTrait.php
  tests/Feature/Flashcard/DeleteFlashCardTest.php
  tests/Siklid/Application/Flashcard/DeleteFlashcardTest.php
Labels: 🚀 Feature, 👊 Blocked

#272 [Box] Update the box voter
  src/Foundation/Security/Authorization/AbstractVoter.php
  src/Siklid/Application/Box/BoxVoter.php
  tests/Siklid/Application/Box/BoxVoterTest.php
Labels: 📝 Task

#173 [Flashcard] View Flashcard
  src/Controller/FlashcardController.php
  src/Siklid/Application/Flashcard/ViewFlashcard.php
  tests/Concern/Factory/FlashcardFactoryTrait.php
  tests/Feature/Flashcard/ViewFlashcardTest.php
Labels: 🚀 Feature

#271 [Foundation][Validation] maintain the validator
  docs/technical/README.md
  docs/technical/basic-workflow/validation.md
  src/Foundation/Http/Request.php
  src/Foundation/Validation/Validator.php
  src/Foundation/Validation/ValidatorInterface.php
  src/Siklid/Application/Box/CreateBox.php
  src/Siklid/Application/Flashcard/CreateFlashcard.php
  tests/Foundation/Http/RequestTest.php
  tests/Foundation/Validation/ValidatorTest.php
Labels: 🧑‍💻 Fix, ⚙️ Foundation

#284 [deps]: bump psalm to v5
  composer.json
  composer.lock
  psalm.xml
  src/Siklid/Repository/BoxRepository.php
Labels: 📝 Task

#286 [deps]: remove patch versions
  composer.json
  composer.lock
Labels: 📝 Task

#296 [Deps] Maintain dependabot config
  .github/dependabot.yaml
Labels: 🧱 Dependencies
